const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetX,
		C3.Plugins.Button.Exps.X,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{cielo: 0},
	{Sólido: 0},
	{Ancla: 0},
	{sueloHitbox: 0},
	{pasto: 0},
	{Plataforma: 0},
	{Jugador: 0},
	{obstaculo: 0},
	{aleatorizador: 0},
	{aleatorizador2: 0},
	{Teclado: 0},
	{textoSolo: 0},
	{cantidad: 0},
	{botones: 0},
	{tienda: 0},
	{Mouse: 0},
	{cerrarTienda: 0},
	{comprarPene1: 0},
	{comprarPene2: 0},
	{comprarPene3: 0},
	{comprarPene4: 0},
	{comprarPene5: 0},
	{precio: 0},
	{AlmacenamientoLocal: 0},
	{mejorarVelocidad1: 0},
	{mejorarVelocidad2: 0},
	{mejorarSpawn1: 0},
	{mejorarSpawn2: 0},
	{Navegador: 0},
	{Audio: 0},
	{nepesTragados: 0},
	{peneActivo: 0},
	{velocidadPenes: 0},
	{CADApSEGUNDO: 0}
];

self.InstanceType = {
	cielo: class extends self.ITiledBackgroundInstance {},
	sueloHitbox: class extends self.ISpriteInstance {},
	pasto: class extends self.ITiledBackgroundInstance {},
	Jugador: class extends self.ISpriteInstance {},
	obstaculo: class extends self.ISpriteInstance {},
	aleatorizador: class extends self.ISpriteInstance {},
	aleatorizador2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	textoSolo: class extends self.ITextInstance {},
	cantidad: class extends self.ITextInstance {},
	botones: class extends self.ISpriteInstance {},
	tienda: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	cerrarTienda: class extends self.IButtonInstance {},
	comprarPene1: class extends self.IButtonInstance {},
	comprarPene2: class extends self.IButtonInstance {},
	comprarPene3: class extends self.IButtonInstance {},
	comprarPene4: class extends self.IButtonInstance {},
	comprarPene5: class extends self.IButtonInstance {},
	precio: class extends self.ISpriteInstance {},
	AlmacenamientoLocal: class extends self.IInstance {},
	mejorarVelocidad1: class extends self.IButtonInstance {},
	mejorarVelocidad2: class extends self.IButtonInstance {},
	mejorarSpawn1: class extends self.IButtonInstance {},
	mejorarSpawn2: class extends self.IButtonInstance {},
	Navegador: class extends self.IInstance {},
	Audio: class extends self.IInstance {}
}